### ISSUE TITLE
Custom provider creation documentation

### ISSUE THREAD

**Issue by fivestones** [yjs/docs#42]
I'm not sure if this should really be called a feature request since its for the docs repository :-) but,

I'd love to know how to make custom provider. I think I could probably figure it out, but I've heard you say in a couple of different videos and I think I've seen you @dmonad write that it's pretty easy to create one. The https://github.com/yjs/docs/blob/main/tutorials/creating-a-custom-provider.md page looks promising but doesn't give me enough to be able to make one. The best idea I have was when you mentioned in a video on youtube that one of the notes apps that uses yjs (I forget which one) had a custom provider which also uses the signal app encryption for its data, but when I went to look at that code, it looked like a complex custom provider.

Anyway, any chance you could take 5 minutes and write up how to make a very basic custom provider, or if there is a write up or simple code example somewhere already that you know about, could you let us know?

Thanks so much. Loving yjs.

**Comment by dmonad** [comment]
Hi @fivestones,

It's all actually already here: https://docs.yjs.dev/api/document-updates

I'm in the process of rewriting the website using an open-source tool. This will also include a dedicated tutorial on how to write a custom provider: https://beta.yjs.dev/docs/tutorials/creating-a-custom-provider

However, note that there are many different ways to implement a provider. Every choice is a tradeoff. Especially when creating an E2E provider, there are many tradeoffs to consider.

It is almost always better to find solutions to specific questions in discuss.yjs.dev or post a new question if your question hasn't been asked yet.

In that regard, Yjs makes it as easy as possible. It exposes an easy & robust document update mechanism that handles many edge cases for you. This is much easier than writing your own conflict resolution algorithm. However, it still requires work and ingenuity on your end. A basic sync protocol between clients, or client-server is very simple. Have a look at the [document-updates sections](https://docs.yjs.dev/api/document-updates).

I want to catch up on the work I missed in the past months, so I'm closing this issue because I don't want to tackle it immediately. Sorry. Hope to help you in the discussion board though.

**Comment by fivestones** [comment]
Thanks, these links are super helpful!
